version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - build

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: master
    jobs:
    - build

jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '11.5.0'

    steps:
    - checkout

    - run:
        name: Make Output Directory
        command: mkdir -p 'artifacts'

    - run:
        name: Build hello-macOS
        command: xcodebuild build -scheme 'hello-macos' | tee 'artifacts/xcode_build_raw.log' | xcpretty

    - store_artifacts:
        path: artifacts
