version: 2.1
jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '13.0.0'

    steps:
    - checkout

    - run: 
        name: Make Output Directory
        command: mkdir -p 'artifacts'

    - run:
        name: Build hello-macOS
        command: xcodebuild build -scheme 'hello-macos' | tee 'artifacts/xcode_build_raw.log' | xcpretty

    - store_artifacts:
        path: artifacts
