version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - build

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build

jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '11.7.0'

    steps:
    - checkout

    # xcode does not like using ssh for some reason
    - run: 'git config --global --unset url."ssh://git@github.com".insteadOf "https://github.com"'

    - run:
        name: Make Output Directory
        command: mkdir -p 'artifacts'

    - run:
        name: Build hello-macOS
        command: xcodebuild build -scheme 'hello-macos' | tee 'artifacts/xcode_build_raw.log' | xcpretty

    - store_artifacts:
        path: artifacts
